spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            authorizationGrantType: authorization_code
            scope: identify,guilds
            redirectUriTemplate: http://aditzel.local:8080/login/oauth2/code/discord
            clientName: discord
        provider:
          discord:
            authorization-uri: https://discordapp.com/api/oauth2/authorize
            token-uri: https://discordapp.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            userNameAttribute: username
  thymeleaf:
    cache: true
discord:
  guildsUrl: https://discordapp.com/api/users/@me/guilds
logging:
  level:
    org.springframework.security: DEBUG
#      org.springframework.boot.autoconfigure.security: DEBUG
#      org.springframework.web: DEBUG
endpoints:
  flyway:
    web:
      enabled: true

