security:
  basic:
    enabled: false
discord:
  client:
    clientId: ${DISCORD_CLIENT_ID}
    clientSecret: ${DISCORD_CLIENT_SECRET}
    accessTokenUri: https://discordapp.com/api/oauth2/token
    userAuthorizationUri: https://discordapp.com/api/oauth2/authorize
#      scope: identify,bot,gdm.join
    scope: identify,guilds
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://discordapp.com/api/users/@me
  user:
    guildsUrl: https://discordapp.com/api/users/@me/guilds
spring:
  thymeleaf:
    cache: true
logging:
  level:
#      org.springframework.security: DEBUG
#      org.springframework.boot.autoconfigure.security: DEBUG
#      org.springframework.web: DEBUG
endpoints:
  flyway:
    web:
      enabled: true

